:book:  doc/development: add devstack notes
kubernetes-sigs/cluster-api-provider-openstack pull request #1569
Opened 2023-05-31 09:53 UTC by tormath1

this is notes from my setup, it can be useful for folks who want to develop CAPO with a single DevStack instance.
<hr>

**What this PR does / why we need it**: This PR adds some documentation notes for CAPO development on a single DevStack instance.

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

2023-06-01 09:48 UTC, dulek requested changes

2023-06-01 09:48 UTC, dulek commented on docs/book/src/development/development.md
> +Admin > Network > Networks > `public` > Subnets > `public-subnet` > Edit Subnet > Subnet Details > :ballot_box_with_check: Enable DHCP + Add DNS
Where's that done?

2023-06-01 09:48 UTC, dulek commented on docs/book/src/development/development.md
> +enable_service rabbit
Not needed, it's in the defaults: https://github.com/openstack/devstack/blob/c424a7a299e37004d318107648bb18e157344985/stackrc#L64-L83

2023-06-01 09:48 UTC, dulek commented on docs/book/src/development/development.md
> +enable_service placement-api placement-client
Same here.

2023-06-02 09:38 UTC, dulek commented on docs/book/src/development/development.md
> +Admin > Network > Networks > `public` > Subnets > `public-subnet` > Edit Subnet > Subnet Details > :ballot_box_with_check: Enable DHCP + Add DNS
Worth to say that. But in general I'd prefer doing that from the CLI instead. I'm guessing it's `enable_dhcp` option on the subnet?

2023-06-02 09:39 UTC, dulek commented on docs/book/src/development/development.md
> +enable_service c-api c-vol c-sch
Hm, maybe one of the plugins disable that? Anyway we get e.g. n-cpu somehow, so I guess it's somewhere else.

2023-06-08 17:25 UTC, tobiasgiese commented
Do you know my WIP PR https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1539? I think this is mainly the same as your documentation

2023-06-21 16:25 UTC, mdbooth approved these changes

2023-09-18 11:07 UTC, lentzi90 reviewed
This has been hanging for a while. I would say it is better to have the notes merged than polishing them forever so merging.
/lgtm
/hold cancel

2023-09-18 11:20 UTC, merged