🌱 Update verbosity levels in instance.go
kubernetes-sigs/cluster-api-provider-openstack pull request #1635
Opened 2023-08-07 20:23 UTC by skylerxhu

**What this PR does / why we need it**:
Checked and updated verbosity levels in cluster-api-provider-openstack/pkg/cloud/services/compute/instance.go to adhere to the guideline https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Which issue(s) this PR fixes** :
Fixes #<1> add `V(2)` to`s.scope.Logger().Info("using existing root volume %s", name)` 
This message should be important to system administrators or operators as it indicates a specific action taken by the system. However, it may not be critical for every developer or user to see this message, hence the choice of verbosity level 2.
Fixes #<2> add `V(4)` to `s.scope.Logger().Info("deleting dangling root volume %s(%s)", volume.Name, volume.ID)`
Since deleting such resources can impact system stability, administrators closely watching the system receive this detailed level 4 message.

/hold

2023-08-08 13:00 UTC, dulek requested changes

2023-08-16 09:48 UTC, mdbooth commented on pkg/cloud/services/compute/instance.go
> +			s.scope.Logger().V(4).Info("deleting dangling root volume %s(%s)", volume.Name, volume.ID)
I would even say 2 in this case because it's directly associated with deleting a resource.

2023-08-16 09:48 UTC, mdbooth commented on pkg/cloud/services/compute/instance.go
> +		s.scope.Logger().V(2).Info("using existing root volume %s", name)
This feels like 'context', so probably a 3.

2023-08-30 13:09 UTC, mdbooth commented
/ok-to-test
/lgtm

2023-08-30 13:10 UTC, mdbooth commented
/hold cancel

2023-08-30 14:32 UTC, merged