🌱 Deduplicate AdoptMachinePorts and AdoptBastionPorts
kubernetes-sigs/cluster-api-provider-openstack pull request #1944
Opened 2024-03-12 18:05 UTC by mdbooth

Both of these methods rely on ReferencedMachineResources and DependentMachineResources, so they can be easily refactored to have a common implementation.

Fixes: #1942 

This PR is based on #1941, so we should merge that first.

TODO:
- [ ] Merge #1941 

/hold

2024-03-13 07:34 UTC, EmilienM commented on pkg/cloud/services/compute/dependent_resources_test.go
can't we keep the tests or did they become useless?

2024-03-13 14:16 UTC, mdbooth commented on pkg/cloud/services/compute/dependent_resources_test.go
The function is such a thin wrapper round Adopt() I didn't think it was worth of its own unit tests. They're all basically adoption tests. You don't agree?

2024-03-13 18:14 UTC, mdbooth commented on pkg/cloud/services/compute/dependent_resources_test.go
Ok, it looks like these were the Adopt tests. I'll resurrect them in port_test.go.

2024-03-14 08:59 UTC, EmilienM commented on pkg/cloud/services/compute/dependent_resources_test.go
Thanks.

2024-03-15 17:43 UTC, mdbooth commented on pkg/cloud/services/compute/dependent_resources_test.go
Bah, forgot. Don't let me forget.

2024-03-15 19:18 UTC, mdbooth commented on pkg/cloud/services/compute/dependent_resources_test.go
I moved them into port_test.go called Test_AdoptPorts, and added a few more.

2024-03-15 19:19 UTC, mdbooth commented
/test pull-cluster-api-provider-openstack-e2e-full-test

2024-03-16 06:54 UTC, EmilienM commented
/test pull-cluster-api-provider-openstack-e2e-full-test

2024-03-16 08:55 UTC, EmilienM commented
/test pull-cluster-api-provider-openstack-e2e-full-test

2024-03-16 20:11 UTC, mdbooth commented
/test pull-cluster-api-provider-openstack-e2e-full-test

2024-03-16 20:17 UTC, mdbooth commented
/test pull-cluster-api-provider-openstack-e2e-full-test

2024-03-18 13:01 UTC, mdbooth commented
/hold cancel

2024-03-18 14:55 UTC, mdbooth commented
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1954 was the root cause of most of the full-test CI failures in this PR. This PR includes a change, which we needed to make anyway, which avoids the issue in most cases: we don't need to re-reconcile if we only adopted. However, the underlying issue remains. I'll push a separate PR to fix that.

2024-03-18 17:02 UTC, dulek requested changes

2024-03-18 17:02 UTC, dulek commented on pkg/cloud/services/compute/dependent_resources.go
> -		return false, err
Seems like this change should be in a different commit? It's syntax error otherwise.

2024-03-19 09:19 UTC, mdbooth commented
> Alright, I only found one issue with a change done in the last commit, when it should be done in the middle one. Let's fix that so that reverts would be possible? Or just squash the commits.

Thanks. I'll tidy them up but keep them separate, as I've been *trying* to make smaller, functional commits. When you look at the next one in this series, though, you'll see how that's going 😟

2024-03-19 09:36 UTC, mdbooth commented
I've cleaned that up and re-run the non-e2e tests against each commit individually. I also rebased on to main to pick up #1955, which is important for this series.

2024-03-19 10:13 UTC, dulek commented
/lgtm

2024-03-19 10:38 UTC, merged