Do not delete bastion floating ip if set in spec
kubernetes-sigs/cluster-api-provider-openstack pull request #2257
Opened 2024-11-18 07:56 UTC by anders-elastisys

**What this PR does / why we need it**:

This PR makes it so that if an floatingIP is set in the `openstackcluster.spec.bastion.floatingIP`, and it is the same as set in the `status` of the `openstackcluster` resource, it will not be deleted when deleting the cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2157 

**Special notes for your reviewer**:

My issue got stale so I am creating this PR so that hopefully this feature does not get forgotten.

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

2024-11-26 13:25 UTC, mdbooth reviewed
/ok-to-test
/lgtm

@EmilienM I think you're the expert in this code.

2024-11-26 15:23 UTC, EmilienM commented on controllers/openstackcluster_controller.go
> +		// Floating IP set in status
this comment doesn't bring value, remove it please.

2024-11-26 15:23 UTC, EmilienM commented on controllers/openstackcluster_controller.go
> +		// Floating IP from the spec
this comment doesn't bring value, remove it please.

2024-11-26 15:25 UTC, EmilienM commented on controllers/openstackcluster_controller.go
> +	if statusFloatingIP != nil && (specFloatingIP == nil || *statusFloatingIP != *specFloatingIP) {
Here please add a comment on what opinionated decision we make.

```
We only remove the bastion's floating IP if it exists and if it's the not same value defined both in the spec and in status. This decision was made so if a user specifies a pre-created floating IP that is intended to be used for the bastion, the floating IP won't get removed once the bastion is destroyed.
```

Or something like that.

2024-11-26 15:25 UTC, EmilienM commented on controllers/openstackcluster_controller.go
> +				// If a floating IP is set for the bastion spec, skip deleting it
same here, put more context in this comment.

2024-11-26 15:28 UTC, EmilienM requested changes
Thanks for your contribution.

I've put some comments inline.
I don't want to be picky but I honestly think we should have e2e coverage for this PR, simply because the code around bastion has proven to break quite easily and I've spent hours fixing it.

Please have a look at how we test a flavor change for the bastion:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/300f85079c9e336986d9637f2b03dce02c824efb/test/e2e/suites/e2e/e2e_test.go#L277

and see if we can do the same kind of testing:
* Create a FIP using Gophercloud
* Update the cluster spec to provide that FIP in Bastion
* Check that the bastion uses that FIP
* Delete the Bastion, make sure the FIP was not deleted
* Delete the FIP

Let me know if it's too much asked, I can help.
If you want to do the tests as a follow-up, we can also do that and in that case I'll approve this PR.

2024-11-26 16:26 UTC, anders-elastisys commented
> Let me know if it's too much asked, I can help. If you want to do the tests as a follow-up, we can also do that and in that case I'll approve this PR.

Thanks for the comments, I will take try to add e2e tests when I get the time, if I am not successful in this I'll let you know.

2024-11-26 16:38 UTC, EmilienM commented
> > Let me know if it's too much asked, I can help. If you want to do the tests as a follow-up, we can also do that and in that case I'll approve this PR.
> 
> Thanks for the comments, I will take try to add e2e tests when I get the time, if I am not successful in this I'll let you know.

awesome; thanks. And if we don't manage it to do it in a timely manner, I can merge as is and do the tests afterwards.

2024-12-23 15:39 UTC, anders-elastisys commented
@EmilienM I updated the code comments as you suggested https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2257/commits/b0ba0469d39fa8ea1659e5a7d3802b90827881e9, I have not had the time to do the tests sadly, can we do this as a separate task or can someone else add this?

2025-01-21 15:42 UTC, anders-elastisys commented
/retest

2025-03-11 10:19 UTC, alexandrevilain requested changes
Hi!

This PR is pretty cool and would help users using Openstack on public cloud providers. In public cloud senarios we don't have enough rights to order again the same floating IP.

We already debated about this issue here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1615#issuecomment-1719670115

@anders-elastisys feel free to ping me if you need help implement e2e tests asked by @EmilienM

2025-03-11 10:19 UTC, alexandrevilain commented on controllers/openstackcluster_controller.go
> +	if openStackCluster.Spec.Bastion.FloatingIP != nil {
```suggestion
	if openStackCluster.Spec.Bastion != nil && openStackCluster.Spec.Bastion.FloatingIP {
```
Looks like this is the reason of failing e2e.

2025-03-17 12:34 UTC, EmilienM commented
/hold cancel
/approve

2025-03-17 17:44 UTC, EmilienM commented
/cherry-pick release-0.12
/lgtm

2025-03-17 18:43 UTC, merged

2025-08-15 05:08 UTC, lentzi90 commented
/retitle :bug: Do not delete bastion floating ip if set in spec