Add doc for how to move a cluster
kubernetes-sigs/cluster-api-provider-openstack pull request #630
Opened 2020-09-01 06:20 UTC by jichenjc

**What this PR does / why we need it**:
Add a doc on how to move a cluster

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2020-09-02 04:13 UTC, jichenjc commented
recheck

2020-09-03 03:10 UTC, jichenjc commented
@hidekazuna @sbueringer take a look? The CI is not stable now (https://github.com/theopenlab/openlab/issues/581) but this is doc only change...

2020-09-03 07:20 UTC, hidekazuna commented
@jichenjc Moving cluster is nothing special except for #626 . IMO we do not need documentation about moving once we resolve #626 .

2020-09-07 13:01 UTC, jichenjc commented
well.. I think it's still helpful to give an end to end sample ..

2020-09-11 23:21 UTC, hidekazuna commented
recheck

2020-10-12 01:13 UTC, hidekazuna commented
@jichenjc Please update using `clusterctl.cluster.x-k8s.io/move`.

2020-10-13 06:10 UTC, jichenjc commented
@hidekazuna updated, thanks~

2020-10-14 05:05 UTC, hidekazuna requested changes
Let's use "OpenStack", not "openstack".

2020-10-14 05:05 UTC, hidekazuna commented on docs/mover.md
> +target cluster (using external cloud manager)
Target cluster (Below is an example of external cloud provider)

2020-10-14 05:05 UTC, hidekazuna commented on docs/mover.md
> +# Install openstack providers into target cluster
Install OpenStack Cluster API provider into target cluster

2020-10-14 07:51 UTC, jichenjc commented
@hidekazuna update. thanks

2020-10-14 09:26 UTC, jichenjc commented
recheck

2020-10-15 00:41 UTC, hidekazuna commented
/lgtm

2020-10-15 00:43 UTC, merged