Add version into log
kubernetes-sigs/cluster-api-provider-openstack pull request #638
Opened 2020-09-22 10:55 UTC by jichenjc

**What this PR does / why we need it**:

add versions of git into manager's log

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2020-09-24 00:08 UTC, jichenjc commented
recheck

2020-09-24 01:45 UTC, jichenjc commented
recheck

2020-09-29 02:15 UTC, hidekazuna requested changes

2020-09-29 02:15 UTC, hidekazuna commented on version/version.go
> +Copyright 2018 The Kubernetes Authors.
now 2020, not 2018.

2020-09-29 02:26 UTC, jichenjc commented on version/version.go
> +Copyright 2018 The Kubernetes Authors.
updated, thanks

2020-09-29 04:05 UTC, hidekazuna commented
/lgtm

2020-09-29 04:05 UTC, merged