🐛 Delete bastion if basion.enabled=false
kubernetes-sigs/cluster-api-provider-openstack pull request #817
Opened 2021-03-30 09:08 UTC by hidekazuna

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #647 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

2021-03-30 11:26 UTC, sbueringer commented
/test pull-cluster-api-provider-openstack-e2e-test

2021-03-30 11:55 UTC, sbueringer requested changes
overall lgtm, just a few nits

2021-03-30 11:55 UTC, sbueringer commented on pkg/cloud/services/compute/bastion.go
> +func (s *Service) DeleteBastion(serverID string, openStackCluster *infrav1.OpenStackCluster) error {
I would hand over the cluster as first parameter for consistency

2021-03-30 11:55 UTC, sbueringer commented on pkg/cloud/services/networking/securitygroups.go
> +func (s *Service) DeleteSecurityGroups(group *infrav1.SecurityGroup, openStackCluster *infrav1.OpenStackCluster) error {
I would hand over the cluster as first parameter

2021-03-30 11:55 UTC, sbueringer commented on controllers/openstackcluster_controller.go
> +	if bastion := openStackCluster.Status.Bastion; bastion != nil {
I wouldn't write this in an additional var. That's usually only done for errors or stuff like map lookups in Golang. So please just use `openStackCluster.Status.Bastion`

2021-03-31 01:19 UTC, hidekazuna commented
@sbueringer fixed.

I will propose another PR to update parameter order for other functions.

2021-03-31 01:39 UTC, jichenjc commented
/lgtm

the param reorder in next PR works for me

2021-03-31 05:04 UTC, sbueringer commented
> @sbueringer fixed.
> 
> I will propose another PR to update parameter order for other functions.

Thx, sounds good to me. I think the following is a good ordering (just an example for when we need *all* of the commonly used parameters):
```go
(ctx context.Context, log logr.Logger, ctrlClient, workloadClient client.Client, kubeClient, workloadKubeClient kubernetes.Interface, patchHelper *patch.Helper, cluster *clusterv1.Cluster, openStackCluster *infrav1.OpenStackCluster, machine *clusterv1.Machine, openstackMachine *infrav1.OpenStackMachine, .... (everything else)) (ctrl.Result, error) 
```
Some background why:
* context first
* then logr.Logger
* first clients for the management cluster, then the ones for the workload clusters
  * sorted per type: we need the controller runtime client more then the regular one (not sure if we need the regular one at all right now, in this repo)
* patchHelper next (also some sort of "client", but not needed that much, and it cannot do that much, so in some way a "smaller" client)
* after that it's just from "bigger" / "more important" resources to smaller ones, and first from the cluster-api repo and then ours
* I would continue this "top down" approach for other parameters (although I don't necessarily would enforce a hard ordering for "everything else")

2021-03-31 05:05 UTC, sbueringer approved these changes

2021-03-31 05:05 UTC, sbueringer commented
/lgtm

2021-03-31 05:44 UTC, hidekazuna commented
Let's merge this.

/hold cancel

2021-03-31 06:54 UTC, merged